### ISSUE TITLE
Recommended record command results in error "setupFilesAfterEnv option"

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-agent-js#164]
I am following the [instructions for recording jest](https://appmap.io/docs/reference/appmap-agent-js.html#tests-recording).

I am using command `@appland/appmap-agent-js` rather than `appmap-agent-js`.

```
$ npx @appland/appmap-agent-js -- jest 'test/**/*.ts'
node:16109) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
● Validation Error:

  Module test/**/*.ts in the setupFilesAfterEnv option was not found.
         <rootDir> is: /Users/kgilpin/source/appland/appmap-js/packages/sequence-diagram

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html
```

**Comment by lachrist** [comment]
I'm not sure what is happening here. I will try to reproduce this tomorrow.

**Comment by lachrist** [comment]
I think there are two issues with your test command:

1) You installed jest globally and it is that version that is running. You want to make sure to use the jest of the project. That would be using `npx jest` or `yarn exec jest` or `yarn run test`. Unfortunately the agent recognizes `npx jest` at the moment.
2) When I run `npx jest 'test/**/*.ts'` (so without involving the agent) I receive this error message: `Invalid testPattern test/**/*.ts supplied. Running all tests instead.`. So I would stick with simply `npx jest`.

I think the correct way to proceed is:

```sh
yarn add @appland/appmap-agent-js
cd packages/sequence-diagram
npx @appland/appmap-agent-js -- npx jest
```

Unfortunately this causes an error which I documented in https://github.com/getappmap/appmap-agent-js/issues/167.

**Comment by kgilpin** [comment]
> npx jest 'test/**/*.ts' (so without involving the agent) I receive this
error message: Invalid testPattern test/**/*.ts supplied. Running all tests
instead.

A got this command suggestion from the docs. So, I think the docs should be
updated.
