### ISSUE TITLE
Recommended record command results in error "TypeError: this._environment.runScript is not a function"

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-agent-js#165]
```
➜  sequence-diagram git:(feat/seq-diagram-diff-text) ✗ npx @appland/appmap-agent-js -- jest              

(node:16544) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 FAIL  tests/unit/http.spec.ts
  ● Test suite failed to run

    TypeError: this._environment.runScript is not a function

      at Runtime._execModule (../../../../../../../usr/local/lib/node_modules/jest/node_modules/jest-runtime/build/index.js:733:41)
```

**Comment by lachrist** [comment]
Apparently this is caused by a clash of jest version. Could it be that your system is running different jest version? Anyhow, I will also try to reproduce this tomorrow.

**Comment by lachrist** [comment]
As for the previous issue, you are running the globally installed `jest`. You want to use the locally installed `jest` with `npx jest`, `yarn exec jest` or `yarn run test`. Only the first one is actually recognized as a `jest` command and it causes https://github.com/getappmap/appmap-agent-js/issues/167.
