### ISSUE TITLE
Telemetry reports environment variable names (not values) in use

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-agent-js#178]

**Comment by lachrist** [comment]
@brikelly I need more context to understand this issue.

**Comment by kgilpin** [comment]
Is this misfiled? I don’t think this has anything to do with the JS agent.

appmap-js has already been enhanced to report env var names.

**Comment by brikelly** [comment]
Yeah this was in the wrong repo and also a duplicate of the issue where this work got done. Closing it now.
