### ISSUE TITLE
TS support decorators 

### ISSUE THREAD

**Issue by OrangeBorning** [getappmap/appmap-agent-js#198]
Hope someone can fix this

`APPMAP-ERROR Unrecoverable parsing error at file "xxxxxx" >> SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): "decorators", "decorators-legacy".
`

**Comment by dividedmind** [comment]
@lachrist just a friendly reminder

**Comment by on21life** [comment]
thank you for your contribution, I was able to solve it!
