### ISSUE TITLE
How I can run this with Angular ? 

### ISSUE THREAD

**Issue by titusfx** [getappmap/appmap-agent-js#204]

**Comment by brikelly** [comment]
Hi @titusfx , you would need to be able to run the Angular app in Node, as that's the engine we have instrumented in order to create AppMaps from JS/TS apps. (FYI @lachrist )

**Comment by ar-IGT** [comment]
So there are no plans to add support for recording process of an Angular app being run in CLI server development mode, i.e. `ng serve` with AppMap?

**Comment by kgilpin** [comment]
At the moment the focus is on Node, but JS Support is planned. I don’t have a date for that yet though.

**Comment by ar-IGT** [comment]
Would be nice if support for Angular 2+ gets added in Q1/Q2.
