### ISSUE TITLE
JS agent should accurately report loops

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-agent-js#212]
Currently, the JS agent does not accurately report loops sometimes.

Example from [this test](https://github.com/getappmap/appmap-js/blob/main/packages/cli/tests/unit/record/testCasesComplete.spec.ts#L61):

![Image](https://user-images.githubusercontent.com/45714532/229626058-bb09af49-1502-4cc9-9048-5eb657e164b6.png)

Another example from [this test](https://github.com/getappmap/appmap-js/blob/main/packages/cli/tests/unit/record/test/areTestCommandsConfigured.spec.ts#L26).

![Image](https://user-images.githubusercontent.com/45714532/229627127-64a8aaf2-9735-4d28-b4ac-a0849e48cd95.png)

**Comment by ahtrotta** [comment]
In both of the examples above, there was **not** a loop in the source code but the appmap reported that there was a loop. Is there any way to differentiate between sequential calls to a function and a loop? How do our other agents handle this situation?

**Comment by ahtrotta** [comment]
Yeah, that makes sense that there's no way. It's just semantically different in the source file.

**Comment by lachrist** [comment]
Yeah the agent records function applications without context. It has no idea whether it is called inside a loop or not.

**Comment by ahtrotta** [comment]
Okay, we can close this issue then.
