### ISSUE TITLE
JS Agent yields appmaps without sequence diagrams

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-agent-js#219]
In our `appmap-js` repository, I ran this command in `packages/cli`:

```
npx @appland/appmap-agent-js@latest -- jest --no-cache
```

And it generated appmaps without a sequence diagram.

As of this writing, the command:
```
npx @appland/appmap-agent-js@latest --version
```
Yields: `@appland/appmap-agent-js@13.8.0`.

**Comment by ahtrotta** [comment]
If you open the appmap and open the `Sequence Diagram` tab, then you'll see that it is blank.

**Comment by ahtrotta** [comment]
![Image](https://user-images.githubusercontent.com/45714532/235216520-0fadd524-e0ba-4b74-a7b4-6ab8ff10dd0e.png)

**Comment by ahtrotta** [comment]
The `Dependency Map` and `Trace View` are not empty, though:


![Image](https://user-images.githubusercontent.com/45714532/235216703-8c05966f-5b5d-48f5-80a4-ec7cd76a0e3d.png)

**Comment by ahtrotta** [comment]
No, I didn't see any console errors. Here's an example appmap file.

[prune subcommand works.zip](https://github.com/getappmap/appmap-agent-js/files/11356196/prune.subcommand.works.zip)

**Comment by dustinbyrne** [comment]
FYI @lachrist, I've seen this happen when code objects (probably packages in particular) are missing from `classMap`.
